
export const orders = [
    { id: "#CK-8821", customer: "Ananya Roy", customerPhone: "+91 98100 11111", customerEmail: "ananya@gmail.com", restaurant: "Biryani Blues", restaurantCity: "Delhi", items: [{ name: "Chicken Biryani", qty: 2, price: 280 }, { name: "Raita", qty: 1, price: 60 }], amount: 640, status: "delivered", time: "2m ago", date: "Mar 4, 2026", city: "Delhi", address: "42, Lajpat Nagar, Delhi" },
    { id: "#CK-8820", customer: "Rishi Kapoor", customerPhone: "+91 97200 22222", customerEmail: "rishi@gmail.com", restaurant: "Pizza Palace", restaurantCity: "Bangalore", items: [{ name: "Margherita Pizza", qty: 1, price: 320 }, { name: "Coke", qty: 1, price: 60 }], amount: 420, status: "in-transit", time: "8m ago", date: "Mar 4, 2026", city: "Bangalore", address: "15, Koramangala, Bangalore" },
    { id: "#CK-8819", customer: "Meera Nair", customerPhone: "+91 96300 33333", customerEmail: "meera@gmail.com", restaurant: "Burger Barn", restaurantCity: "Mumbai", items: [{ name: "Classic Burger", qty: 1, price: 199 }], amount: 199, status: "preparing", time: "12m ago", date: "Mar 4, 2026", city: "Mumbai", address: "8, Bandra West, Mumbai" },
    { id: "#CK-8818", customer: "Arjun Dev", customerPhone: "+91 95400 44444", customerEmail: "arjun@gmail.com", restaurant: "Tandoor Tales", restaurantCity: "Pune", items: [{ name: "Dal Makhani", qty: 2, price: 240 }, { name: "Butter Naan", qty: 4, price: 160 }, { name: "Lassi", qty: 2, price: 120 }], amount: 890, status: "delivered", time: "18m ago", date: "Mar 4, 2026", city: "Pune", address: "23, Koregaon Park, Pune" },
    { id: "#CK-8817", customer: "Kavya Reddy", customerPhone: "+91 94500 55555", customerEmail: "kavya@gmail.com", restaurant: "Wok This Way", restaurantCity: "Hyderabad", items: [{ name: "Hakka Noodles", qty: 1, price: 220 }, { name: "Spring Rolls", qty: 2, price: 130 }], amount: 350, status: "cancelled", time: "25m ago", date: "Mar 4, 2026", city: "Hyderabad", address: "11, Banjara Hills, Hyderabad" },
    { id: "#CK-8816", customer: "Saurabh Jain", customerPhone: "+91 93600 66666", customerEmail: "saurabh@gmail.com", restaurant: "Biryani Blues", restaurantCity: "Delhi", items: [{ name: "Mutton Biryani", qty: 3, price: 960 }, { name: "Shorba", qty: 1, price: 80 }], amount: 1200, status: "delivered", time: "31m ago", date: "Mar 4, 2026", city: "Delhi", address: "7, Saket, Delhi" },
    { id: "#CK-8815", customer: "Divya Iyer", customerPhone: "+91 92700 77777", customerEmail: "divya@gmail.com", restaurant: "Pizza Palace", restaurantCity: "Bangalore", items: [{ name: "Farmhouse Pizza", qty: 1, price: 299 }], amount: 299, status: "preparing", time: "45m ago", date: "Mar 4, 2026", city: "Bangalore", address: "3, Indiranagar, Bangalore" },
    { id: "#CK-8814", customer: "Rohan Mehta", customerPhone: "+91 91800 88888", customerEmail: "rohan@gmail.com", restaurant: "Dosa Delight", restaurantCity: "Bangalore", items: [{ name: "Masala Dosa", qty: 2, price: 180 }, { name: "Filter Coffee", qty: 2, price: 80 }], amount: 440, status: "delivered", time: "1h ago", date: "Mar 4, 2026", city: "Bangalore", address: "19, Jayanagar, Bangalore" },
    { id: "#CK-8813", customer: "Pooja Sharma", customerPhone: "+91 90900 99999", customerEmail: "pooja@gmail.com", restaurant: "Rolls & Wraps", restaurantCity: "Delhi", items: [{ name: "Paneer Roll", qty: 3, price: 270 }, { name: "Fries", qty: 1, price: 80 }], amount: 380, status: "cancelled", time: "1h ago", date: "Mar 4, 2026", city: "Delhi", address: "55, Rajouri Garden, Delhi" },
    { id: "#CK-8812", customer: "Vikram Singh", customerPhone: "+91 89000 00000", customerEmail: "vikram@gmail.com", restaurant: "Tandoor Tales", restaurantCity: "Pune", items: [{ name: "Paneer Tikka", qty: 2, price: 380 }, { name: "Roti", qty: 4, price: 80 }], amount: 580, status: "in-transit", time: "1h ago", date: "Mar 4, 2026", city: "Pune", address: "31, Viman Nagar, Pune" },
];